POST http://localhost:3000/posts
Content-Type: application/json

{

  "title": "Post Title",
  "postType": "post",
  "slug": "post-name-123-12",
  "status": "scheduled",
  "content": "Post Content",
  "schema": "{\r\n \"@context\": \"https:\\/\\/schema.org\", \r\n \"@type\": \"Person\"\r\n }",
  "featuredImageUrl": "http://post-image.jpg",
  "publishedOn": "2024-03-16T07:46:32.000Z",
  "tags": [1,4],
  "metaOptions": {
       "metaValue" : "{\"sidebarEnabled\": true, \"footerActive\": true}"
  },
  "authorId":1
}